<a href="https://colab.research.google.com/github/d0k7/Pattern-Recognition-Machine-Learning-Lab-Code/blob/main/PR_%26_ML_LAB_CODE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1) Data pre-processing using Python Machine Learning libraries/ MATLAB.

In [1]:
#importing libraries
import numpy as np
import pandas as pd

# Importing dataset
dataset = pd.read_csv('/content/Data.csv')
x = dataset.iloc[:, :-1].values  # Independent variable matrix
y = dataset.iloc[:, 3].values     # Dependent vector variable

print(x)
print(y)



#Handling missing data
# Using SimpleImputer to handle missing values
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')  # Automatically handles NaN values

# Fit the imputer to the columns with missing values (columns 1 and 2)
imputer = imputer.fit(x[:, 1:3])

# Transform the dataset by replacing missing values with the mean of respective columns
x[:, 1:3] = imputer.transform(x[:, 1:3])

print(x)



#Encoding categoricaal data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x=LabelEncoder()
x[:,0]=labelencoder_x.fit_transform(x[:,0])
print(x[:,0])

# Define the ColumnTransformer
column_transformer = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])],  # Apply OneHotEncoder to the first column
    remainder='passthrough'  # Keep the remaining columns unchanged
)

x = column_transformer.fit_transform(x)

print(x)




# Label encoding the dependent variable y (if it's categorical)
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

print(y)






#splitting dataset into traning set and testing set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.2, random_state=0)
print(x_train, x_test, y_train, y_test)



#feature scaling
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)
print(x_train)
print(x_test)



[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
[0 2 1 2 1 0 2 0 1 0]
[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1 0 1]
[[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0

Q2) Design a model to predict the housing price from Boston Dataset using Multivariate Linear Regression.